CC=g++  -std=c++14 

all: test
test: run

callbacks_on_tokenizr: callbacks_on_tokenizr.cpp catch.hpp Makefile
	$(CC) -g -o callbacks_on_tokenizr callbacks_on_tokenizr.cpp

run: callbacks_on_tokenizr 
	./callbacks_on_tokenizr  


